Lmod Warning:
-------------------------------------------------------------------------------
The following dependent module(s) are not currently loaded: gcc/12.4.0
(required by: R/4.4.2), gcc/14.2.0 (required by: openblas/0.3.28)
-------------------------------------------------------------------------------




The following have been reloaded with a version change:
  1) python/3.12.1 => python/3.9.0

--- Logging error ---
--- Logging error ---
Traceback (most recent call last):
  File "/scratch/users/salber/packages/miniconda3/envs/CellVoyager/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/scratch/users/salber/packages/miniconda3/envs/CellVoyager/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/home/groups/jamesz/salber/CellVoyager/tests/single_ablation_test.py", line 100, in <module>
    sys.exit(main())
  File "/home/groups/jamesz/salber/CellVoyager/tests/single_ablation_test.py", line 73, in main
    results = tester.test_agent(
  File "/home/groups/jamesz/salber/CellVoyager/tests/base_tester.py", line 105, in test_agent
    agent.run()
  File "/home/groups/jamesz/salber/CellVoyager/agent.py", line 1074, in run
    past_analyses = self.execute_idea(analysis, past_analyses, analysis_idx)
  File "/home/groups/jamesz/salber/CellVoyager/agent.py", line 912, in execute_idea
    self.logger.log_response(f"STEP {iteration + 1} RAN SUCCESSFULLY - Analysis {analysis_idx+1}", f"step_execution_success_{step_name}")
  File "/home/groups/jamesz/salber/CellVoyager/logger.py", line 52, in log_response
    self.logger.info(f"RESPONSE/OUTPUT: {source}\n\n{response_text}")
Message: 'RESPONSE/OUTPUT: step_execution_success_1_3\n\nSTEP 3 RAN SUCCESSFULLY - Analysis 1'
Arguments: ()
slurmstepd: error: *** JOB 3801312 ON sh04-05n01 CANCELLED AT 2025-08-16T00:24:52 DUE TO TIME LIMIT ***
